### ISSUE TITLE
help

### ISSUE THREAD

**Issue by x3was** [cedricalpatch/rpf_gamemode#1]
Error running system event handling function for resource rpf_main: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: modules/server/db.lua:55: attempt to index a nil value (global 'MySQL')
stack traceback:
        modules/server/db.lua:55: in field 'FindPlayer'
        server/session.lua:39: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:219: in function <citizen:/scripting/lua/scheduler.lua:218>

**Comment by cedricalpatch** [comment]
Hello
Do you have been added the sql manualy?
The deploy_db.sql

**Comment by x3was** [comment]
its inly two rows plary and onther thing right ?

**Comment by cedricalpatch** [comment]
I dont understand your question?

**Comment by x3was** [comment]
the db only two rows on data , player and other table i did add sql manualy

**Comment by cedricalpatch** [comment]
yes but the script need the table for work ...

**Comment by cedricalpatch** [comment]
for next version that work fully for weapon and blackmoney
